//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CISERPEntities : DbContext
    {
        public CISERPEntities()
            : base("name=CISERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<BoardMaster> BoardMasters { get; set; }
        public virtual DbSet<BranchTab> BranchTabs { get; set; }
        public virtual DbSet<CasteMaster> CasteMasters { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<ClassMaster> ClassMasters { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentFamilyDetail> StudentFamilyDetails { get; set; }
        public virtual DbSet<StudentGenaralDetail> StudentGenaralDetails { get; set; }
        public virtual DbSet<StudentOfficialDetail> StudentOfficialDetails { get; set; }
        public virtual DbSet<StudentPreviousSchool> StudentPreviousSchools { get; set; }
        public virtual DbSet<StudentSubjectAllotment> StudentSubjectAllotments { get; set; }
    }
}
