//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubjectAllotment
    {
        public int Id { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string StudentName { get; set; }
        public string SubjectAlloted { get; set; }
        public string Remark { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Medium { get; set; }
        public string Groupe { get; set; }
    }
}
