//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFamilyDetail
    {
        public int Id { get; set; }
        public string StEnRCode { get; set; }
        public string SrNo { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherDesignation { get; set; }
        public string FatherQualification { get; set; }
        public string FatherIncomeMonthly { get; set; }
        public string FatherOfficeAddress { get; set; }
        public string FatherContactNo { get; set; }
        public string FatherEmail { get; set; }
        public string FamilyIncomeMonthly { get; set; }
        public string FamilyRelationship { get; set; }
        public string FamilyEmail { get; set; }
        public string FamilyGuardianName { get; set; }
        public string FamilyContactNo { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherDesignation { get; set; }
        public string MotherQualification { get; set; }
        public string MotherIncomeMonthly { get; set; }
        public string MotherOfficeAddress { get; set; }
        public string MotherContactNo { get; set; }
        public string MotherEmail { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Withdrwal { get; set; }
    }
}
