//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPreviousSchool
    {
        public int Id { get; set; }
        public string StEnRCode { get; set; }
        public string SrNo { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Board { get; set; }
        public string Medium { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Marks { get; set; }
        public string Percentage { get; set; }
        public string SchoolName { get; set; }
        public string Schooladdress { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Withdrwal { get; set; }
    }
}
