//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGenaralDetail
    {
        public int Id { get; set; }
        public string StEnRCode { get; set; }
        public string SrNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string SiblingCategory { get; set; }
        public string SBSrNo { get; set; }
        public string SBStName { get; set; }
        public string SBFathersName { get; set; }
        public string SBClass { get; set; }
        public string SBSection { get; set; }
        public string PhysicallDisabledCategory { get; set; }
        public string PhyStName { get; set; }
        public string PhyStDetail { get; set; }
        public string StLocalAddress { get; set; }
        public Nullable<int> StLocalStateId { get; set; }
        public Nullable<int> StLocalCityId { get; set; }
        public string StLocalZip { get; set; }
        public string StPerAddress { get; set; }
        public Nullable<int> StPerStateId { get; set; }
        public Nullable<int> StPerCityId { get; set; }
        public string StPerZip { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string Category { get; set; }
        public string Caste { get; set; }
        public string BloodGroup { get; set; }
        public string HouseName { get; set; }
        public string Withdrwal { get; set; }
    }
}
