//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOfficialDetail
    {
        public int Id { get; set; }
        public string StEnRCode { get; set; }
        public string SrNo { get; set; }
        public Nullable<System.DateTime> DateOfAdmiission { get; set; }
        public Nullable<int> AdmissionForClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string GroupNa { get; set; }
        public string FileNo { get; set; }
        public string Reference { get; set; }
        public string Remark { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Withdrwal { get; set; }
        public string Medium { get; set; }
        public string Board { get; set; }
        public string TypeOFAdmision { get; set; }
        public string Promotion { get; set; }
        public string Card { get; set; }
        public string HostelRequired { get; set; }
        public string TransportRequired { get; set; }
        public string BusLocationName { get; set; }
        public string WayAmount { get; set; }
        public string OneTwoWay { get; set; }
        public string VehicleType { get; set; }
        public string HouseName { get; set; }
        public string LibraryRequired { get; set; }
        public string StudentPassword { get; set; }
        public string GuardianPassword { get; set; }
    }
}
